chore: fix lint error

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -1,45 +1,70 @@
 #!/bin/sh
 
-set -e
+go mod tidy
+if [ $? != 0 ]; then
+    echo >&2 "go mod tidy failed"
+    exit 1
+fi
+git add go.mod
+git add go.sum
 
-# Function to check the last command status
-check_status() {
+# format golang files
+
+swag fmt
+
+STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=d | grep ".go$")
+
+for FILE in $STAGED_GO_FILES
+do
+    goimports -w $FILE
     if [ $? != 0 ]; then
-        echo >&2 "$1 failed"
+        echo >&2 "goimports failed"
         exit 1
     fi
-}
 
-# Run go mod tidy and check for errors
-go mod tidy
-check_status "go mod tidy"
+    gofumpt -w $FILE
+    if [ $? != 0 ]; then
+        echo >&2 "gofumpt failed"
+        exit 1
+    fi
 
-# Stage go.mod and go.sum files
-git add go.mod go.sum
+    tagalign -fix -sort -order "gorm,json,binding" -strict $FILE
 
-# Format Go files
-STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=d | grep ".go$" || true)
+    gci write --custom-order -s standard -s localmodule -s default $FILE
 
-if [ -z "$STAGED_GO_FILES" ]; then
-    echo "No Go files to format"
-else
-    for FILE in $STAGED_GO_FILES; do
-        goimports -w "$FILE"
-        check_status "goimports on $FILE"
+    git add $FILE
+done
 
-        gofumpt -w "$FILE"
-        check_status "gofumpt on $FILE"
+# golangci-lint check
 
-        git add "$FILE"
-    done
+golangci-lint run
+
+if [ $? != 0 ]; then
+    echo >&2 "golangci-lint failed"
+    exit 1
 fi
 
-# Run golangci-lint and check for errors
-golangci-lint run
-check_status "golangci-lint"
 
-# Run go test and check for errors
+# go test
+
+CONTAINS_CHAT=false
+for FILE in $STAGED_GO_FILES
+do
+    if [[ $FILE == *"app/service/chat"* ]]; then
+        CONTAINS_CHAT=true
+        break
+    fi
+done
+
+if [ "$CONTAINS_CHAT" = false ]; then
+    export DISABLE_TEST_CHAT=true
+fi
+
 go test -v ./...
-check_status "go test"
+
+if [ $? != 0 ]; then
+    echo >&2 "go test failed"
+    exit 1
+fi
 
 exit 0
